# Generated by Django 5.2 on 2025-06-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_listing_user_id_listing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('Dostępne', 'Available'), ('Sprzedane', 'Sold'), ('Zarezerwowane', 'Reserved')], default='Dostępne', max_length=20),
        ),
    ]
